In [1]:
%matplotlib qt
import numpy as np
np.random.seed(2022)
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import scipy.stats as stats

In [2]:
#Let's create some data and rotate it as we did already
#Cigar
x_1=np.random.normal(loc=3,scale=0.8,size=100)
x_2=np.random.normal(loc=1,scale=0.4,size=100)
x_3=np.random.normal(loc=4,scale=0.4,size=100)

x=np.array([x_1,x_2,x_3])


fig = plt.figure()
ax = fig.add_subplot(projection='3d')

ax.scatter(x[0],x[1],x[2],color='r')

#ax.plot(x_1,x_2,'r+',zdir='z')
#ax.plot(x_1,x_3,'g+',zdir='y')
#ax.plot(x_2,x_3,'k+',zdir='x')


ax.set_xlabel(r'$x_1$')
ax.set_ylabel(r'$x_2$')
ax.set_zlabel(r'$x_3$')

ax.set_xlim((-2,6))
ax.set_ylim((-2,6))
ax.set_zlim((-2,6))


(-2.0, 6.0)

In [3]:
X=x.T
print(X.shape)
X


(100, 3)


array([[2.99957768, 0.8852414 , 3.82453092],
       [2.78007886, 0.34353026, 4.02824973],
       [2.88857155, 0.1942033 , 4.09494081],
       [4.58774893, 0.84772857, 3.79665261],
       [3.22568746, 1.33628014, 3.85557811],
       [3.60864693, 0.57360436, 3.49112361],
       [3.24078528, 1.15701467, 4.01597713],
       [3.43223782, 0.99316678, 4.56288852],
       [3.29879783, 1.23198741, 3.846133  ],
       [3.30225072, 1.06832418, 4.21554586],
       [2.92782945, 1.10298608, 4.22059656],
       [1.15524538, 0.93009816, 3.65259479],
       [3.91420802, 0.89511695, 3.36414575],
       [1.77147657, 0.4030704 , 3.9026222 ],
       [2.30899839, 0.79453007, 4.13357404],
       [3.81323595, 1.1209293 , 4.12290695],
       [3.82717111, 0.32598577, 3.812304  ],
       [2.34040622, 1.72408543, 4.15167393],
       [3.01512389, 0.90742367, 4.14003085],
       [2.69332516, 0.80654816, 3.99217261],
       [2.75665162, 0.51572844, 4.43344789],
       [3.7978332 , 0.30585863, 4.08803143],
       [2.

Typically, the rows are the samples, the columns are the features, the measured variables.

Sometimes it is the other way around. Not too important, can work with transposed matrices: $X^T$. 

Keep in mind that for matrix products:

$(\hat{A}\hat{B})^T=\hat{B}^T\hat{A}^T$

when transposing a product, you need to reverse the order of multiplications.

Simple proof:

We know that: $(\hat{A}\hat{B})_{i,j}=\sum_kA_{i,k}B_{k,j}$

so:

$(\hat{A}\hat{B})^T_{i,j}=(\hat{A}\hat{B})_{j,i}=\sum_kA_{j,k}B_{k,i}=
\sum_kA^T_{k,j}B^T_{i,k}=\sum_kB^T_{i,k}A^T_{k,j}=(\hat{A}^T\hat{B}^T)_{i,j}$

#### Covariance matrix 

Matrix of the measure of spread along the coordinate axes.  

Analogous to covariance between two random variables:

$cov(x,y)=\overline{(x-\bar{x})(y-\bar{y})}$

we can calculate the covariances between any two variabales we measured in a sample:

$cov(x_i,x_j)=\overline{(x_i-\bar{x_i})(x_j-\bar{x_j})}$

This is the $i,j$ element of the matrix.

The covariance matrix is:

If the data matrix is $X$ then the centered data matrix is:

$X_c=X-\bar{X}$

Remember that the averaging is over samples!


In [4]:
#Let's center our data
#First let's calciulate \bar{X}
X_bar=np.mean(X,axis=0)
X_bar.view()

array([2.99348363, 1.0037916 , 4.03013164])

In [5]:
#Let's center the data
X_c=X-X_bar
X_c.view()

array([[ 6.09405031e-03, -1.18550206e-01, -2.05600726e-01],
       [-2.13404770e-01, -6.60261340e-01, -1.88191453e-03],
       [-1.04912080e-01, -8.09588302e-01,  6.48091676e-02],
       [ 1.59426530e+00, -1.56063036e-01, -2.33479035e-01],
       [ 2.32203830e-01,  3.32488537e-01, -1.74553528e-01],
       [ 6.15163296e-01, -4.30187241e-01, -5.39008027e-01],
       [ 2.47301654e-01,  1.53223069e-01, -1.41545150e-02],
       [ 4.38754185e-01, -1.06248272e-02,  5.32756875e-01],
       [ 3.05314199e-01,  2.28195809e-01, -1.83998641e-01],
       [ 3.08767085e-01,  6.45325732e-02,  1.85414214e-01],
       [-6.56541845e-02,  9.91944796e-02,  1.90464919e-01],
       [-1.83823825e+00, -7.36934417e-02, -3.77536849e-01],
       [ 9.20724389e-01, -1.08674653e-01, -6.65985888e-01],
       [-1.22200706e+00, -6.00721201e-01, -1.27509440e-01],
       [-6.84485245e-01, -2.09261530e-01,  1.03442402e-01],
       [ 8.19752318e-01,  1.17137699e-01,  9.27753047e-02],
       [ 8.33687476e-01, -6.77805838e-01

In [15]:


fig = plt.figure()
ax = fig.add_subplot(projection='3d')

ax.scatter(X_c.T[0],X_c.T[1],X_c.T[2])

#ax.scatter(x[0],x[1],x[2],color='r')

#ax.plot(x_1,x_2,'r+',zdir='z')
#ax.plot(x_1,x_3,'g+',zdir='y')
#ax.plot(x_2,x_3,'k+',zdir='x')


ax.set_xlabel(r'$x_1$')
ax.set_ylabel(r'$x_2$')
ax.set_zlabel(r'$x_3$')

ax.set_xlim((-3,3))
ax.set_ylim((-3,3))
ax.set_zlim((-3,3))

ax.set_title('Centered')

Text(0.5, 0.92, 'Centered')

We can get the covariance matrix by simple multiplication of the centered data matrix, and dividing by the sample size minus 1: $n-1$.

First, note that the centered matrix rows are the variables $x_i$ for each sample $j$, minus the sample average $\bar{x_i}$:

$X_{j,i}=x_i(sample\ j)-\bar{x_i}$

The transposed matrix $X^T$ is:

$X^T_{i,j}=x_i(sample\ j)-\bar{x_i}$


Remember that:

$(AB)_{i,j}=\sum_{k=1}^n A_{i,k}B_{k,j}$

So:

$(X^T_cX_c)_{i,j}=\sum_{k=1}^nX^T_{i,k}X_{k,j}$

or:

$(X^T_cX_c)_{i,j}=\sum_{k=1}^n(x_i(sample\ k)-\bar{x_k})(x_j(sample\ k)-\bar{x_j})$

similar to:

$\sum_{k=1}^n(x(sample\ k)-\bar{x})(y(sample\ k)-\bar{y})$

of:

$\sum_{k=1}^n(x_k-\bar{x})(y_k-\bar{y})$

where he index $k$ goes over samples.

So the covariance matrix is:

$K=\frac{1}{n-1}X^T_cX_c$

Be carefull, sometimes it is all transposed!

In [7]:
print(X_c.shape)

(100, 3)


In [8]:
#Let's do it for our data, remember our n is 100

K=np.matmul(X_c.T,X_c)/(99)
K

array([[0.5894005 , 0.02265871, 0.03434024],
       [0.02265871, 0.15928863, 0.01088912],
       [0.03434024, 0.01088912, 0.17536593]])

Note that it is not normalized to the product of standard deviations.

In [9]:
#Numpy has a function that will do the same
#Note the transposition here :( 

K_np=np.cov(X.T)
K_np

array([[0.5894005 , 0.02265871, 0.03434024],
       [0.02265871, 0.15928863, 0.01088912],
       [0.03434024, 0.01088912, 0.17536593]])

In [10]:
#We can calculate the standard deviations (the diagonal elements).
#Just take the square root of it. 

np.sqrt(K_np)

array([[0.76772423, 0.15052811, 0.1853112 ],
       [0.15052811, 0.39910979, 0.10435097],
       [0.1853112 , 0.10435097, 0.41876715]])

Remember how we created the data:

x_1=np.random.normal(loc=3,scale=0.8,size=100)

x_2=np.random.normal(loc=1,scale=0.4,size=100)

x_3=np.random.normal(loc=4,scale=0.4,size=100)

So the standard deviations are just about right.

Remember what the covariance matrix is:

$K=\begin{pmatrix}var(x_1) & cov(x_1,x_2) & cov(x_1,x_3)\\
                  cov(x_2,x_1) & var(x_2) & cov(x_2,x_3)\\
                  cov(x_3,x_1) & cov(x_3,x_2) & var(x_3)
\end{pmatrix}$



Now let's rotate the data around the z axis by 45 degrees, $\pi/4$ radians.

In [14]:
phi=np.pi/4
R=np.array([[np.cos(phi),-np.sin(phi),0],[np.sin(phi),np.cos(phi),0],[0,0,1]])

X_rot=np.matmul(R,X_c.T)

fig = plt.figure()
ax = fig.add_subplot(projection='3d')

ax.scatter(X_rot[0],X_rot[1],X_rot[2])

#ax.scatter(x[0],x[1],x[2],color='r')

#ax.plot(x_1,x_2,'r+',zdir='z')
#ax.plot(x_1,x_3,'g+',zdir='y')
#ax.plot(x_2,x_3,'k+',zdir='x')


ax.set_xlabel(r'$x_1$')
ax.set_ylabel(r'$x_2$')
ax.set_zlabel(r'$x_3$')

ax.set_xlim((-3,3))
ax.set_ylim((-3,3))
ax.set_zlim((-3,3))
ax.set_title('Rotated')

Text(0.5, 0.92, 'Rotated')

In [12]:
#Now calculate K for the rotated X
K_rot=np.cov(X_rot)
K_rot


array([[0.35168585, 0.21505594, 0.01658244],
       [0.21505594, 0.39700327, 0.03198199],
       [0.01658244, 0.03198199, 0.17536593]])

In [13]:
K_np

array([[0.5894005 , 0.02265871, 0.03434024],
       [0.02265871, 0.15928863, 0.01088912],
       [0.03434024, 0.01088912, 0.17536593]])

##### Important: The K matrix is diagonal if the spread is greatest along the axes. 

If we change the axes to be along the greatest spread, the K matrix will turn into diagonal.