In [1]:
%matplotlib qt
import numpy as np
np.random.seed(2022)
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import scipy.stats as stats

# PCA imports
from sklearn.decomposition import PCA


### Principal Component Analysis

The goal of PCA is to find the axis of the greatest spread in the data, PC1. 

Then the axis of the second greatest spread, PC2, the PC3 and so on...

After that, once you know the vectors that define these axes, you can project the data on that subspace. 

The space of two greatest spreads is (PC1, PC2), you can choose the two next after PC1, (PC2, PC3) etc.


##### The principal components are the Eigenvectors of the Covariance matrix.

The Eigenvectors are the PC axes. 

The Eigenvales "explain" the variances. 

Note that in the coordinate system where the axes align with the directions of greatest spread, the covariance matrix is diagonal. 

If we create different variables, linear combos of the original ones, 
the K matrix on the diagonal has the variances of these new variables. 

In [2]:
#Example
x=np.array([[0,0],[1,1],[2,2],[3,3],[4,4],[1,3],[3,1]])
print(x.shape)

fig =plt.figure()
ax=fig.add_subplot()
ax.scatter(x.T[0],x.T[1])
ax.set_aspect('equal')
plt.xlabel(r'$x_1$')
plt.ylabel(r'$x_2$')

(7, 2)


Text(0, 0.5, '$x_2$')

In [3]:
#Let's assemble the covariance matrix
K=np.cov(x.T)
K

array([[2.        , 1.33333333],
       [1.33333333, 2.        ]])

In [4]:
#Let's solve the eigenproblem for K
w,v=np.linalg.eig(K)
print("The eigen values are:",w)
print("The eigenvectors are:",v)

The eigen values are: [3.33333333 0.66666667]
The eigenvectors are: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


So the eigenvectors are:

$PC1=\frac{1}{2}\begin{pmatrix}1\\1\end{pmatrix}$ with eigenvalue $w_1=6.6$

and 

$PC2=\frac{1}{2}\begin{pmatrix}1\\-1\end{pmatrix}$ with eigenvalue $w_1=3.3$

Here I ordered the eigenvalues from larger to smaller.

To go from the original coordinate system 
$x_1=\begin{pmatrix}1\\0\end{pmatrix}$ and $x_2=\begin{pmatrix}0\\1\end{pmatrix}$

to the new one, we need to rotate by 45 degrees clockwise with:

$R=\begin{pmatrix}cos(\pi/4)&sin(\pi/4)\\-sin(\pi/4)&cos(\pi/4)\end{pmatrix}$

In [5]:
#First, lets find the means:
x_bar=np.mean(x,axis=0)
x_bar

array([2., 2.])

In [6]:
#Then center the data
x_c=x-x_bar
x_c

fig =plt.figure()
ax=fig.add_subplot()
ax.scatter(x_c.T[0],x_c.T[1])
ax.set_aspect('equal')
plt.xlabel(r'$x_1$')
plt.ylabel(r'$x_2$')

Text(0, 0.5, '$x_2$')

In [7]:
#Then rotate clockwise by 45 degrees
R=[[np.cos(np.pi/4),np.sin(np.pi/4)],[-np.sin(np.pi/4),np.cos(np.pi/4)]]

x_pca=np.matmul(R,x_c.T)

fig =plt.figure()
ax=fig.add_subplot()
ax.scatter(x_pca[0],x_pca[1])
ax.set_aspect('equal')
plt.xlabel(r'$x_1$')
plt.ylabel(r'$x_2$')


Text(0, 0.5, '$x_2$')

###### Let's try the same in 3D

In [8]:
#Let's cretae the data first.
x_1=np.random.normal(loc=3,scale=1.0,size=100)
x_2=np.random.normal(loc=2,scale=0.8,size=100)
x_3=np.random.normal(loc=1,scale=0.01,size=100)

x=np.array([x_1,x_2,x_1+2*x_2])

#Rotate with our matrix, around (1,1,1)
#R=np.array([[0,1,0],[0,0,1],[1,0,0]])

fig = plt.figure()
ax = fig.add_subplot(projection='3d')

#ax.scatter(x_r[0],x_r[1],x_r[2])

ax.scatter(x[0],x[1],x[2],color='b')

ax.plot(x[0],x[1],'r+',zdir='z')
ax.plot(x[0],x[2],'g+',zdir='y')
ax.plot(x[1],x[2],'k+',zdir='x')


ax.set_xlabel(r'$x_1$')
ax.set_ylabel(r'$x_2$')
ax.set_zlabel(r'$x_3$')

ax.set_xlim((-1,8))
ax.set_ylim((-1,6))
ax.set_zlim((-1,15))

(-1.0, 15.0)

In [9]:
#Let's cretae the data first.
x_1=np.random.normal(loc=3,scale=1.0,size=100)
x_2=np.random.normal(loc=2,scale=0.8,size=100)
x_3=np.random.normal(loc=1,scale=0.01,size=100)

x=np.array([x_1,x_2,x_1+2*x_2])

#Rotate with our matrix, around (1,1,1)
#R=np.array([[0,1,0],[0,0,1],[1,0,0]])

fig = plt.figure()
ax = fig.add_subplot(projection='3d')

#ax.scatter(x_r[0],x_r[1],x_r[2])

ax.scatter(x[0],x[1],x[2],color='b')

#ax.plot(x[0],x[1],'r+',zdir='z')
#ax.plot(x[0],x[2],'g+',zdir='y')
#ax.plot(x[1],x[2],'k+',zdir='x')


ax.set_xlabel(r'$x_1$')
ax.set_ylabel(r'$x_2$')
ax.set_zlabel(r'$x_3$')

ax.set_xlim((-1,15))
ax.set_ylim((-1,15))
ax.set_zlim((-1,15))

(-1.0, 15.0)

In [10]:
#Let's calculate the cov matrix
K=np.cov(x)
K

array([[0.84173877, 0.05053622, 0.94281121],
       [0.05053622, 0.74488086, 1.54029793],
       [0.94281121, 1.54029793, 4.02340707]])

In [11]:
# finding principle components
pca = PCA(n_components = 3) # this defines the model
#x_fit=pca.fit(x.T) # this fits the model
# a good measure of performance
#print('Variance Explained: ', pca.explained_variance_ratio_)

# PCA vizualization
X_pca = pca.fit_transform(x.T) # transform the dafiginto PCA space
print('Variance Explained: ', pca.explained_variance_ratio_)

fig =plt.figure()
ax=fig.add_subplot()
ax.scatter(X_pca[:,0],X_pca[:,1])
ax.set_aspect('equal')
ax.set_xlim([-6,6])
ax.set_ylim([-6,6])
plt.xlabel('PC1')
plt.ylabel('PC2')

Variance Explained:  [8.61876379e-01 1.38123621e-01 1.87583898e-31]


Text(0, 0.5, 'PC2')

In [12]:
fig =plt.figure()
ax=fig.add_subplot()
ax.scatter(X_pca[:,0],X_pca[:,2])
ax.set_aspect('equal')
ax.set_xlim([-6,6])
ax.set_ylim([-6,6])
plt.xlabel('PC1')
plt.ylabel('PC3')

Text(0, 0.5, 'PC3')

In [13]:
fig =plt.figure()
ax=fig.add_subplot()
ax.scatter(X_pca[:,1],X_pca[:,2])
ax.set_aspect('equal')
ax.set_xlim([-6,6])
ax.set_ylim([-6,6])
plt.xlabel('PC2')
plt.ylabel('PC3')

Text(0, 0.5, 'PC3')

In [14]:
#Let's cretae the data first.
x_1=np.random.normal(loc=1,scale=1.0,size=100)
x_2=np.random.normal(loc=1,scale=1.2,size=100)
x_3=np.random.normal(loc=1,scale=0.7,size=100)

x=np.array([x_1,x_2,x_1+2*x_2+x_3])

#Rotate with our matrix, around (1,1,1)
#R=np.array([[0,1,0],[0,0,1],[1,0,0]])

fig = plt.figure()
ax = fig.add_subplot(projection='3d')

#ax.scatter(x_r[0],x_r[1],x_r[2])

ax.scatter(x[0],x[1],x[2],color='b')

#ax.plot(x[0],x[1],'r+',zdir='z')
#ax.plot(x[0],x[2],'g+',zdir='y')
#ax.plot(x[1],x[2],'k+',zdir='x')


ax.set_xlabel(r'$x_1$')
ax.set_ylabel(r'$x_2$')
ax.set_zlabel(r'$x_3$')

ax.set_xlim((-10,10))
ax.set_ylim((-10,10))
ax.set_zlim((-10,15))

(-10.0, 15.0)

In [15]:
# finding principle components
pca = PCA(n_components = 3) # this defines the model
#x_fit=pca.fit(x.T) # this fits the model
# a good measure of performance
#print('Variance Explained: ', pca.explained_variance_ratio_)

# PCA vizualization
X_pca = pca.fit_transform(x.T) # transform the dafiginto PCA space
print('Variance Explained: ', pca.explained_variance_ratio_)

fig =plt.figure()
ax=fig.add_subplot()
ax.scatter(X_pca[:,0],X_pca[:,1])
ax.set_aspect('equal')
ax.set_xlim([-10,10])
ax.set_ylim([-10,10])
plt.xlabel('PC1  '+str(100*round(pca.explained_variance_ratio_[0],3))+'%')
plt.ylabel('PC2  '+str(100*round(pca.explained_variance_ratio_[1],3))+'%')

Variance Explained:  [0.89129524 0.1016083  0.00709646]


Text(0, 0.5, 'PC2  10.2%')

In [16]:
fig =plt.figure()
ax=fig.add_subplot()
ax.scatter(X_pca[:,0],X_pca[:,2])
ax.set_aspect('equal')
ax.set_xlim([-10,10])
ax.set_ylim([-10,10])
plt.xlabel('PC1 '+str(100*round(pca.explained_variance_ratio_[0],3))+'%')
plt.ylabel('PC3 '+str(100*round(pca.explained_variance_ratio_[2],3))+'%')

Text(0, 0.5, 'PC3 0.7000000000000001%')

In [17]:
fig =plt.figure()
ax=fig.add_subplot()
ax.scatter(X_pca[:,1],X_pca[:,2])
ax.set_aspect('equal')
ax.set_xlim([-6,6])
ax.set_ylim([-6,6])
plt.xlabel('PC2 '+str(100*round(pca.explained_variance_ratio_[1],3))+'%')
plt.ylabel('PC3 '+str(100*round(pca.explained_variance_ratio_[2],3))+'%')

Text(0, 0.5, 'PC3 0.7000000000000001%')

#### Dimensionality reduction

PCA can be used to reduce the dimensionality of the data, so we can proceed with another type of analysis.

After we reduce the dimensions, we can cluster, for example.

In [21]:
#Let's create two clusters

#Let's cretae the data first.
z_1=np.random.normal(loc=1,scale=1.0,size=100)
z_2=np.random.normal(loc=1,scale=1.2,size=100)
z_3=np.random.normal(loc=1,scale=0.7,size=100)

y_1=np.random.normal(loc=5,scale=0.1,size=100)
y_2=np.random.normal(loc=5,scale=1.2,size=100)
y_3=np.random.normal(loc=5,scale=1.0,size=100)

x_1=np.concatenate((y_1,z_1),axis=0)
x_2=np.concatenate((y_2,z_2),axis=0)
x_3=np.concatenate((y_3,z_3),axis=0)

x=np.array([x_1,x_2,x_1+2*x_2+x_3])


#Rotate with our matrix, around (1,1,1)
#R=np.array([[0,1,0],[0,0,1],[1,0,0]])

fig = plt.figure()
ax = fig.add_subplot(projection='3d')

#ax.scatter(x_r[0],x_r[1],x_r[2])

ax.scatter(x[0],x[1],x[2],color='b')

#ax.plot(x[0],x[1],'r+',zdir='z')
#ax.plot(x[0],x[2],'g+',zdir='y')
#ax.plot(x[1],x[2],'k+',zdir='x')


ax.set_xlabel(r'$x_1$')
ax.set_ylabel(r'$x_2$')
ax.set_zlabel(r'$x_3$')

ax.set_xlim((-10,25))
ax.set_ylim((-10,25))
ax.set_zlim((-10,25))

(-10.0, 25.0)

In [24]:
# finding principle components
pca = PCA(n_components = 3) # this defines the model
#x_fit=pca.fit(x.T) # this fits the model
# a good measure of performance
#print('Variance Explained: ', pca.explained_variance_ratio_)

# PCA vizualization
X_pca = pca.fit_transform(x.T) # transform the data into PCA space
print('Variance Explained: ', pca.explained_variance_ratio_)

fig =plt.figure()
ax=fig.add_subplot()
ax.scatter(X_pca[:,0],X_pca[:,1])
ax.set_aspect('equal')
ax.set_xlim([-20,20])
ax.set_ylim([-20,20])
plt.xlabel('PC1  '+str(100*round(pca.explained_variance_ratio_[0],3))+'%')
plt.ylabel('PC2  '+str(100*round(pca.explained_variance_ratio_[1],3))+'%')

fig =plt.figure()
ax=fig.add_subplot()
ax.scatter(X_pca[:,0],X_pca[:,2])
ax.set_aspect('equal')
ax.set_xlim([-20,20])
ax.set_ylim([-20,20])
plt.xlabel('PC1  '+str(100*round(pca.explained_variance_ratio_[0],3))+'%')
plt.ylabel('PC3  '+str(100*round(pca.explained_variance_ratio_[2],3))+'%')

fig =plt.figure()
ax=fig.add_subplot()
ax.scatter(X_pca[:,1],X_pca[:,2])
ax.set_aspect('equal')
ax.set_xlim([-20,20])
ax.set_ylim([-20,20])
plt.xlabel('PC2  '+str(100*round(pca.explained_variance_ratio_[1],3))+'%')
plt.ylabel('PC3  '+str(100*round(pca.explained_variance_ratio_[2],3))+'%')

Variance Explained:  [0.9887569  0.00966381 0.00157928]


Text(0, 0.5, 'PC3  0.2%')

Let's do one last example

In [45]:
z_1=np.random.normal(loc=1,scale=2.0,size=100)
z_2=np.random.normal(loc=1,scale=2.0,size=100)
z_3=np.random.normal(loc=1,scale=0.7,size=100)

y_1=np.random.normal(loc=-1,scale=0.2,size=10)
y_2=np.random.normal(loc=-1,scale=0.2,size=10)
y_3=np.random.normal(loc=10,scale=0.2,size=10)

x_1=np.concatenate((y_1,z_1),axis=0)
x_2=np.concatenate((y_2,z_2),axis=0)
x_3=np.concatenate((y_3,z_3),axis=0)

x=np.array([x_1,x_2,x_1+2*x_2+x_3])


#Rotate with our matrix, around (1,1,1)
#R=np.array([[0,1,0],[0,0,1],[1,0,0]])

fig = plt.figure()
ax = fig.add_subplot(projection='3d')

#ax.scatter(x_r[0],x_r[1],x_r[2])

ax.scatter(x[0],x[1],x[2],color='b')

#ax.plot(x[0],x[1],'r+',zdir='z')
#ax.plot(x[0],x[2],'g+',zdir='y')
#ax.plot(x[1],x[2],'k+',zdir='x')


ax.set_xlabel(r'$x_1$')
ax.set_ylabel(r'$x_2$')
ax.set_zlabel(r'$x_3$')

ax.set_xlim((-10,25))
ax.set_ylim((-10,25))
ax.set_zlim((-10,25))

(-10.0, 25.0)

In [46]:
# finding principle components
pca = PCA(n_components = 3) # this defines the model
#x_fit=pca.fit(x.T) # this fits the model
# a good measure of performance
#print('Variance Explained: ', pca.explained_variance_ratio_)

# PCA vizualization
X_pca = pca.fit_transform(x.T) # transform the data into PCA space
print('Variance Explained: ', pca.explained_variance_ratio_)

fig =plt.figure()
ax=fig.add_subplot()
ax.scatter(X_pca[:,0],X_pca[:,1])
ax.set_aspect('equal')
ax.set_xlim([-20,20])
ax.set_ylim([-20,20])
plt.xlabel('PC1  '+str(100*round(pca.explained_variance_ratio_[0],3))+'%')
plt.ylabel('PC2  '+str(100*round(pca.explained_variance_ratio_[1],3))+'%')

fig =plt.figure()
ax=fig.add_subplot()
ax.scatter(X_pca[:,0],X_pca[:,2])
ax.set_aspect('equal')
ax.set_xlim([-20,20])
ax.set_ylim([-20,20])
plt.xlabel('PC1  '+str(100*round(pca.explained_variance_ratio_[0],3))+'%')
plt.ylabel('PC3  '+str(100*round(pca.explained_variance_ratio_[2],3))+'%')

fig =plt.figure()
ax=fig.add_subplot()
ax.scatter(X_pca[:,1],X_pca[:,2])
ax.set_aspect('equal')
ax.set_xlim([-20,20])
ax.set_ylim([-20,20])
plt.xlabel('PC2  '+str(100*round(pca.explained_variance_ratio_[1],3))+'%')
plt.ylabel('PC3  '+str(100*round(pca.explained_variance_ratio_[2],3))+'%')

Variance Explained:  [0.82490126 0.13304561 0.04205313]


Text(0, 0.5, 'PC3  4.2%')

PCA can give wrong picture of the details normal to the PC1-PC2 plane. 