Let's explore a few more features of numpy; still in one dimension

In [1]:
import numpy as np
np.set_printoptions(precision=3) 
import matplotlib.pyplot as plt

In [2]:
print(np.__version__)

1.21.5


In [3]:
# default type conversions
a = np.array([1, 2, 3])
print(a)
print(a.size)
print(type(a))
print(a.dtype)

[1 2 3]
3
<class 'numpy.ndarray'>
int64


In [4]:
c = np.array([1, 2.1, 3]) # standard upcast #cast: change the type
print('c=', c)
print(c.dtype)
d = np.array([1, 2.6, 3], dtype='int') # fractional part is discarded
print('d=', d)

c= [1.  2.1 3. ]
float64
d= [1 2 3]


In [5]:
a = [1 2 3] # unfortunately cannot make arrays like that

SyntaxError: invalid syntax (3765575891.py, line 1)

In [8]:
e = np.empty(10, dtype='int') # get whatever is in the memory; no initiliazation cost
print('e =', e) # for the hackers out there

e = [                  0                  20                   0
                   0 4613349223037927424 3761968254896189494
 3833739095573553453 3258183018689147956 4135818719030425188
     137586666594659]


In [13]:
import numpy as np
np.set_printoptions(precision=3) 
import matplotlib.pyplot as plt
# generate random numbers
# setting seed has pros and cons
np.random.seed(20220926) # this is not a very random starting point

In [11]:
# uniform random numbers between 0 and 1
ra = np.random.random(25)
print(ra)
rb=np.random.random(25)
print(rb)

[0.686 0.347 0.972 0.133 0.237 0.084 0.441 0.571 0.264 0.681 0.563 0.21
 0.926 0.527 0.346 0.914 0.717 0.439 0.013 0.864 0.513 0.675 0.215 0.251
 0.622]
[0.588 0.535 0.28  0.481 0.762 0.405 0.111 0.438 0.653 0.075 0.402 0.997
 0.031 0.764 0.027 0.783 0.486 0.763 0.941 0.596 0.645 0.68  0.501 0.997
 0.545]


In [14]:
ra = np.random.random(25)
print(ra)
rb=np.random.random(25)
print(rb)

[0.686 0.347 0.972 0.133 0.237 0.084 0.441 0.571 0.264 0.681 0.563 0.21
 0.926 0.527 0.346 0.914 0.717 0.439 0.013 0.864 0.513 0.675 0.215 0.251
 0.622]
[0.588 0.535 0.28  0.481 0.762 0.405 0.111 0.438 0.653 0.075 0.402 0.997
 0.031 0.764 0.027 0.783 0.486 0.763 0.941 0.596 0.645 0.68  0.501 0.997
 0.545]


In [15]:
nra = np.random.normal(2, 0.1, 10)
print(nra)
#plt.hist(nra)

[2.027 2.104 1.968 2.038 2.115 2.121 2.224 2.018 2.135 1.995]


In [16]:
# from, to, dimensions of array
ri = np.random.randint(0, 10, 25) # last int not included
print(ri)

[6 5 5 4 6 9 3 0 0 0 0 8 3 9 4 5 4 2 0 2 4 1 8 6 0]


In [17]:
# accessing elements start:stop:step
print(ri[2:15:3])

[5 9 0 8 4]


In [18]:
# accessing elements
print(ri[15:2:-3])

[5 3 0 3 4]


In [19]:
ri[15]

5

In [20]:
# accessing elements
print(ri[2::6])

[5 0 4 4]


In [21]:
print(ri[::-1])

[0 6 8 1 4 2 0 2 4 5 4 9 3 8 0 0 0 0 3 9 6 4 5 5 6]


In [22]:
ri[:]

array([6, 5, 5, 4, 6, 9, 3, 0, 0, 0, 0, 8, 3, 9, 4, 5, 4, 2, 0, 2, 4, 1,
       8, 6, 0])

In [23]:
riv = ri[::2] #change both arraies
print(riv)

[6 5 6 3 0 0 3 4 4 0 4 8 0]


In [24]:
# idea of views
riv[0] = 100 #change both arries
print(ri)
print(riv)

[100   5   5   4   6   9   3   0   0   0   0   8   3   9   4   5   4   2
   0   2   4   1   8   6   0]
[100   5   6   3   0   0   3   4   4   0   4   8   0]


In [25]:
# more on views
rri = ri[::-1]
#print(id(ri), id(rri))
rri[0] = 3131
print(rri)
print(ri)
print(riv)

[3131    6    8    1    4    2    0    2    4    5    4    9    3    8
    0    0    0    0    3    9    6    4    5    5  100]
[ 100    5    5    4    6    9    3    0    0    0    0    8    3    9
    4    5    4    2    0    2    4    1    8    6 3131]
[ 100    5    6    3    0    0    3    4    4    0    4    8 3131]


In [26]:
cri = ri.copy() #use array.copy()to copy the array without changing the origin array
cri[0] = -1
print(cri)
print(ri)

[  -1    5    5    4    6    9    3    0    0    0    0    8    3    9
    4    5    4    2    0    2    4    1    8    6 3131]
[ 100    5    5    4    6    9    3    0    0    0    0    8    3    9
    4    5    4    2    0    2    4    1    8    6 3131]


In [27]:
# using boolean expressions to select elements
ar = np.random.random(20) * 10
print(ar)

[8.829 5.227 9.714 7.644 4.247 1.867 3.491 4.784 1.193 5.296 4.875 4.978
 4.819 0.105 9.639 0.792 0.935 4.627 1.749 0.337]


In [28]:
print(ar>5)

[ True  True  True  True False False False False False  True False False
 False False  True False False False False False]


In [29]:
print(ar[ar>5])

[8.829 5.227 9.714 7.644 5.296 9.639]


In [30]:
ar[ar>5].mean()

7.725004563783443